# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('singleuse', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Component')),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.AdministratorAccess')),
                ('components', models.ManyToManyField(to='cicada_backend.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('date_fulfilled', models.DateTimeField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('ktp_no', models.CharField(max_length=17)),
                ('npwp_no', models.CharField(blank=True, max_length=15)),
                ('phone_no', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.AdministratorAccess')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('regex', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('is_multivalue_question', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Component')),
            ],
        ),
        migrations.CreateModel(
            name='UserComponentNotificationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Component')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Notification')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Profile')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Response')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(through='cicada_backend.UserNotificationFeed', to='cicada_backend.Notification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='responses',
            field=models.ManyToManyField(through='cicada_backend.UserComponentNotificationResponse', to='cicada_backend.Response'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Question'),
        ),
        migrations.AddField(
            model_name='paymentresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Response'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Response'),
        ),
        migrations.AddField(
            model_name='bill',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Component'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='form_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.FormResponse'),
        ),
    ]
