# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
