# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0002_auto_20170304_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='type',
            field=models.CharField(choices=[('P', 'Payment'), ('F', 'Form')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
