# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0003_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='value',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
