# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0004_form_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='due_date',
        ),
    ]
