# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0005_remove_form_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponentnotificationresponse',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Component'),
        ),
    ]
