# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0007_auto_20170312_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Profile'),
            preserve_default=False,
        ),
    ]
