# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0009_auto_20170312_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='type',
        ),
        migrations.AddField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='response',
            name='value',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
