# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0010_auto_20170312_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='response',
            name='created',
        ),
        migrations.RemoveField(
            model_name='response',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='response',
            name='value',
        ),
        migrations.AlterField(
            model_name='usercomponentnotificationresponse',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.SimpleResponse'),
        ),
    ]
