# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0011_auto_20170312_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='components',
        ),
    ]
