# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0013_notification_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='component',
            new_name='components',
        ),
    ]
