# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0014_auto_20170313_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.AdministratorAccess'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cicada_backend.Organization'),
        ),
    ]
