# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0015_auto_20170313_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='singleuse',
            new_name='single_use',
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
