# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0016_auto_20170313_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.CharField(default='Hehehehehe', max_length=200),
            preserve_default=False,
        ),
    ]
