# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0017_notification_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='value',
            new_name='json_schema',
        ),
        migrations.AddField(
            model_name='form',
            name='ui_schema',
            field=models.TextField(default='ui schema'),
            preserve_default=False,
        ),
    ]
