# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0018_auto_20170315_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField()),
                ('component_id', models.IntegerField()),
            ],
        ),
    ]
