# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicada_backend', '0019_globaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldata',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
